var fs = require('fs');
var path = require('path');

// Application names
exports.appName = 'Mike Demo App';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
exports.gcmServerApiKey = 'YOUR_SERVER_KEY';




//--- Helper functions ---

function readCredentialsFile(name) {
  return fs.readFileSync(
    path.resolve(__dirname, 'credentials', name),
    'UTF-8'
  );
}